### ISSUE TITLE
lots of new features to be add

### ISSUE THREAD

**Issue by meet7202** [meet7202/Fast-Terminal#1]
There are many similar hacktypers available on internet which has more features so our goal is to implement that some of that features in this repository.

Links for Similar Hacktyper:
[Hacktyper 1](http://hackertyper.com/)
[Hacktyper 2](http://thepierealm.coffeecup.com/hackerTyper/)
[Hacktyper 3](http://fediafedia.com/neo/scp/)

**Comment by chiragchevli** [comment]
Hello Owner...
I am Chirag Chevli(DAIICT) and want to contribute to Your Repository(Fast-Terminal).
Here is my Linked In Account Link (https://www.linkedin.com/in/chiragchevli/)
can u guide from Where Should I Start? #DWOC

**Comment by meet7202** [comment]
@chiragchevli try to understand logic of current repository in js of script. explore more such websites provided above and you will find that there are lots of features that you can add. You can refer to last merged pull request so you can see that how you can add small features by adding some code in repository. Feel free to send pull requests :)

Best of Luck. Keep Improving !!
